version: '3'
services:
  web:
    build: .
    command: gunicorn routes:app -b 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:6
